### POST create request to blog server
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title": "제목",
  "content": "내용"
}


### GET 블로그 전체 목록 조회
GET http://localhost:8080/api/articles


### 블로그 게시글 단건 조회
GET http://localhost:8080/api/articles/2


### DELETE 블로그 게시글 단건 삭제
DELETE http://localhost:8080/api/articles/1


### PUT 블로그 게시글 수정
PUT http://localhost:8080/api/articles/9
Content-Type: application/json

{
  "title": "제목9999999",
  "content": "내용9999999"
}


### POST 블로그 댓글 정보 생성
POST http://localhost:8080/api/articles/1/comments
Content-Type: application/json

{
  "body": "댓글 내용4444"
}


### GET 블로그 댓글 정보 조회
GET http://localhost:8080/api/comments/1


### PUT 블로그 댓글 정보 수정
PUT http://localhost:8080/api/comments/1
Content-Type: application/json

{
  "body": "수정된 댓글"
}

### DELETE 블로그 댓글 정보 삭제
DELETE http://localhost:8080/api/comments/1


### GET 게시글과 댓글 정보 한번에 조회
GET http://localhost:8080/api/articles/1/comments